---
-
  date: 2014-07-11
  title: 【ギー秋】第06回ゆる飲み
  url: https://www.facebook.com/events/249990331861241/
-
  date: 2014-07-03
  title: ギー秋もくもく会
  url: http://connpass.com/event/7299/
-
  date: 2014-06-20
  title: 【ギー秋】第05回ゆる飲み
  url: https://www.facebook.com/events/302898069869238/
-
  date: 2014-04-23
  title: ギー秋もくもく会
  url: http://connpass.com/event/5977/
-
  date: 2014-02-22
  title: Arduino会
  url: https://www.facebook.com/events/502755733175268/
-
  date: 2014-02-21
  title: 【ギー秋】第05回ゆる飲み
  url: https://www.facebook.com/events/702674786421262/
-
  date: 2014-02-05
  title: ギー秋もくもく会
  url: http://connpass.com/event/5042/
-
  date: 2014-01-31
  title: 【ギー秋】第04回ゆる飲み
  url: https://www.facebook.com/events/1398119377109136/
-
  date: 2014-01-30
  title: ギー秋もくもく会
  url: http://connpass.com/event/4959/
-
  date: 2014-01-22
  title: ギー秋もくもく会
  url: http://connpass.com/event/4800/
-
  date: 2014-01-13
  title: ギー秋もくもく会
  url: http://connpass.com/event/4767/
-
  date: 2014-01-10
  title: 【ギー秋】第03回ゆる飲み
  url: https://www.facebook.com/events/563155803761683/
-
  date: 2013-12-29
  title: Arduino会
  url:
-
  date: 2013-12-25
  title: ギー秋もくもく会
  url: http://connpass.com/event/4526/
-
  date: 2013-12-20
  title: 【金曜巡回】第02回ゆる飲み@ギークハウス秋葉原
  url: https://www.facebook.com/events/604928396243283/
-
  date: 2013-12-17
  title: ギー秋もくもく会
  url: http://connpass.com/event/4465/
-
  date: 2013-12-11
  title: ギー秋もくもく会
  url: http://www.zusaar.com/event/2427005
-
  date: 2013-11-29
  title: 【隔週金曜日】第01回ゆる飲み@ギークハウス秋葉原
  url: https://www.facebook.com/events/623690321021251/
