---
-
  date: 2014-01-10
  title: 【ギー秋】第03回ゆる飲み
  url: https://www.facebook.com/events/563155803761683/
-
  date: 2013-12-29
  title: Arduino会
  url:
-
  date: 2013-12-25
  title: ギー秋もくもく会
  url: http://connpass.com/event/4526/
-
  date: 2013-12-20
  title: 【金曜巡回】第02回ゆる飲み@ギークハウス秋葉原
  url: https://www.facebook.com/events/604928396243283/
-
  date: 2013-12-17
  title: ギー秋もくもく会
  url: http://connpass.com/event/4465/
-
  date: 2013-12-11
  title: ギー秋もくもく会
  url: http://www.zusaar.com/event/2427005
-
  date: 2013-11-29
  title: 【隔週金曜日】第01回ゆる飲み@ギークハウス秋葉原
  url: https://www.facebook.com/events/623690321021251/
